# Dependabot configuration
version: 2

updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "BinFlip"  # Replace with your GitHub username
    assignees:
      - "BinFlip"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore patch updates for specific packages if needed
      - dependency-name: "goblin"
        update-types: ["version-update:semver-patch"]

  # Fuzzing dependencies
  - package-ecosystem: "cargo"
    directory: "/fuzz"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fuzz-deps"
    labels:
      - "dependencies"
      - "fuzzing"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
