# Code Coverage Configuration for llvm-cov

[run]
branch = true
source = "src"

[report]
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    
    # Don't complain about missing debug-only code:
    "fn fmt",
    "unreachable!",
    "unimplemented!",
    "panic!",
    
    # Don't complain if tests don't hit defensive assertion code:
    "assert!",
    "debug_assert!",
    
    # Don't complain if non-runnable code isn't run:
    "if false",
    "if 0",
    
    # Don't complain about abstract methods, they aren't run:
    "raise AssertionError",
    "raise NotImplementedError",
    
    # Don't complain about test helper functions
    "#\\[cfg\\(test\\)\\]",
    "mod tests",
]

[html]
directory = "target/coverage"

[xml]
output = "target/coverage.xml"
