name: Bug Report
description: Create a report to help us improve dotscope
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load assembly with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: sample-file
    attributes:
      label: Sample File
      description: |
        If possible, please provide a sample .NET assembly file that reproduces the issue.
        You can attach files by dragging them into this text area.
        If the file contains sensitive information, please create a minimal test case.
      placeholder: Attach sample file or describe how to obtain one...

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue.
      render: rust
      placeholder: |
        use dotscope::CilObject;
        
        fn main() -> Result<(), Box<dyn std::error::Error>> {
            let assembly = CilObject::from_file("sample.dll".as_ref())?;
            // ... code that triggers the bug
            Ok(())
        }
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste the full error message or stack trace.
      render: text
      placeholder: Paste error output here...

  - type: input
    id: dotscope-version
    attributes:
      label: dotscope Version
      description: What version of dotscope are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using?
      placeholder: "1.70.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system?
      placeholder: "Windows 11, macOS 13.0, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What architecture are you running on?
      options:
        - x86_64
        - aarch64 (ARM64)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: true
        - label: I am using the latest version of dotscope
          required: false
